In [116]:
import pandas as pd
import numpy as np
import seaborn as sbn

In [104]:
df_fifa = pd.read_csv("fifaplayers_pt.csv")

In [105]:
df_fifa.head()

,id,nome,idade,nacionalidade,pontuação geral,potencial,time,valor,remuneração,perna de preferência,...,emprestado de,validade do contrato,altura,peso,controle de bola,arrancada,agilidade,equilíbrio,energia,força
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Esquerda,...,NaN,2021,5'7,159lbs,96.0,91.0,91.0,95.0,72.0,59.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Direita,...,NaN,2022,6'2,183lbs,94.0,89.0,87.0,70.0,88.0,79.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Direita,...,NaN,2022,5'9,150lbs,95.0,94.0,96.0,84.0,81.0,49.0
3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Direita,...,NaN,2020,6'4,168lbs,42.0,57.0,60.0,43.0,43.0,64.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Direita,...,NaN,2023,5'11,154lbs,91.0,78.0,79.0,77.0,90.0,75.0

In [106]:
df_fifa.tail()

,id,nome,idade,nacionalidade,pontuação geral,potencial,time,valor,remuneração,perna de preferência,...,emprestado de,validade do contrato,altura,peso,controle de bola,arrancada,agilidade,equilíbrio,energia,força
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,Direita,...,NaN,2019,5'9,134lbs,43.0,54.0,60.0,76.0,40.0,47.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,Direita,...,NaN,2020,6'3,170lbs,40.0,41.0,38.0,52.0,43.0,67.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,Direita,...,NaN,2021,5'8,148lbs,44.0,70.0,50.0,58.0,55.0,32.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,Direita,...,NaN,2019,5'10,154lbs,52.0,61.0,52.0,71.0,40.0,48.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,Direita,...,NaN,2019,5'10,176lbs,51.0,57.0,55.0,63.0,47.0,60.0

In [107]:
df_fifa.columns = ['id', 'nome', 'idade', 'nacionalidade', 'pontuacao_geral', 'potencial',
       'time', 'valor', 'remuneracao', 'perna_preferencia',
       'reputaçao_internacional', 'posição', 'camisa', 'contratacao',
       'emprestado_de', 'validade_contrato', 'altura', 'peso',
       'controle_bola', 'arrancada', 'agilidade', 'equilibrio', 'energia',
       'força']

In [35]:
df_fifa.set_index("id", inplace=True)

In [108]:
df_fifa

,id,nome,idade,nacionalidade,pontuacao_geral,potencial,time,valor,remuneracao,perna_preferencia,...,emprestado_de,validade_contrato,altura,peso,controle_bola,arrancada,agilidade,equilibrio,energia,força
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Esquerda,...,NaN,2021,5'7,159lbs,96.0,91.0,91.0,95.0,72.0,59.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Direita,...,NaN,2022,6'2,183lbs,94.0,89.0,87.0,70.0,88.0,79.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Direita,...,NaN,2022,5'9,150lbs,95.0,94.0,96.0,84.0,81.0,49.0
3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Direita,...,NaN,2020,6'4,168lbs,42.0,57.0,60.0,43.0,43.0,64.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Direita,...,NaN,2023,5'11,154lbs,91.0,78.0,79.0,77.0,90.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,Direita,...,NaN,2019,5'9,134lbs,43.0,54.0,60.0,76.0,40.0,47.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,Direita,...,NaN,2020,6'3,170lbs,40.0,41.0,38.0,52.0,43.0,67.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,Direita,...,NaN,2021,5'8,148lbs,44.0,70.0,50.0,58.0,55.0,32.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,Direita,...,NaN,2019,5'10,154lbs,52.0,61.0,52.0,71.0,40.0,48.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,Direita,...,NaN,2019,5'10,176lbs,51.0,57.0,55.0,63.0,47.0,60.0

## Quantos jogadores tem nacionalidade Argentina
Resposta: 937 Jogadores

In [109]:
df_nacionalidade_argentina = df_fifa.loc[df_fifa['nacionalidade'] == "Argentina"]

In [110]:
df_nacionalidade_argentina.head()

,id,nome,idade,nacionalidade,pontuacao_geral,potencial,time,valor,remuneracao,perna_preferencia,...,emprestado_de,validade_contrato,altura,peso,controle_bola,arrancada,agilidade,equilibrio,energia,força
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Esquerda,...,NaN,2021,5'7,159lbs,96.0,91.0,91.0,95.0,72.0,59.0
15,211110,P. Dybala,24,Argentina,89,94,Juventus,€89M,€205K,Esquerda,...,NaN,2022,5'10,165lbs,92.0,87.0,91.0,85.0,80.0,65.0
23,153079,S. Agüero,30,Argentina,89,89,Manchester City,€64.5M,€300K,Direita,...,NaN,2021,5'8,154lbs,89.0,88.0,86.0,91.0,76.0,73.0
38,167664,G. Higuaín,30,Argentina,88,88,Milan,€57M,€245K,Direita,...,Juventus,"Jun 30, 2019",6'1,196lbs,85.0,73.0,75.0,69.0,70.0,85.0
43,201399,M. Icardi,25,Argentina,87,90,Inter,€64.5M,€130K,Direita,...,NaN,2021,5'11,165lbs,81.0,77.0,76.0,76.0,72.0,76.0

In [111]:
df_nacionalidade_argentina['nacionalidade'].value_counts()

Argentina    937
Name: nacionalidade, dtype: int64

# Quantos Jogadores Brasileiros jogam no Barcelona?
Resposta: 4 jogadores Brasileiro que jogam no Barcelona

In [44]:
df_fifa.head()

,nome,idade,nacionalidade,pontuacao_geral,potencial,time,valor,remuneração,perna_preferencia,reputaçao_internacional,...,emprestado_de,validade_contrato,altura,peso,controle_bola,arrancada,agilidade,equilibrio,energia,força
id,,,,,,,,,,,,,,,,,,,,,
158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Esquerda,5.0,...,NaN,2021,5'7,159lbs,96.0,91.0,91.0,95.0,72.0,59.0
20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Direita,5.0,...,NaN,2022,6'2,183lbs,94.0,89.0,87.0,70.0,88.0,79.0
190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Direita,5.0,...,NaN,2022,5'9,150lbs,95.0,94.0,96.0,84.0,81.0,49.0
193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Direita,4.0,...,NaN,2020,6'4,168lbs,42.0,57.0,60.0,43.0,43.0,64.0
192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Direita,4.0,...,NaN,2023,5'11,154lbs,91.0,78.0,79.0,77.0,90.0,75.0

In [52]:
df_fifa.query('nacionalidade == "Brazil" & time == "FC Barcelona"')

,nome,idade,nacionalidade,pontuacao_geral,potencial,time,valor,remuneração,perna_preferencia,reputaçao_internacional,...,emprestado_de,validade_contrato,altura,peso,controle_bola,arrancada,agilidade,equilibrio,energia,força
id,,,,,,,,,,,,,,,,,,,,,
189242,Coutinho,26,Brazil,88,89,FC Barcelona,€69.5M,€340K,Direita,3.0,...,NaN,2023,5'8,150lbs,92.0,89.0,92.0,93.0,79.0,61.0
230658,Arthur,21,Brazil,82,90,FC Barcelona,€32.5M,€125K,Direita,1.0,...,NaN,2024,5'7,161lbs,83.0,68.0,79.0,86.0,78.0,62.0
222737,Malcom,21,Brazil,82,89,FC Barcelona,€31.5M,€140K,Esquerda,2.0,...,NaN,2023,5'8,163lbs,85.0,87.0,92.0,84.0,74.0,64.0
201400,Rafinha,25,Brazil,82,87,FC Barcelona,€29.5M,€165K,Esquerda,2.0,...,NaN,2020,5'9,157lbs,84.0,71.0,80.0,80.0,67.0,66.0

In [54]:
df_fifa.query('nacionalidade == "Brazil" & time == "FC Barcelona"')

,nome,idade,nacionalidade,pontuacao_geral,potencial,time,valor,remuneração,perna_preferencia,reputaçao_internacional,...,emprestado_de,validade_contrato,altura,peso,controle_bola,arrancada,agilidade,equilibrio,energia,força
id,,,,,,,,,,,,,,,,,,,,,
189242,Coutinho,26,Brazil,88,89,FC Barcelona,€69.5M,€340K,Direita,3.0,...,NaN,2023,5'8,150lbs,92.0,89.0,92.0,93.0,79.0,61.0
230658,Arthur,21,Brazil,82,90,FC Barcelona,€32.5M,€125K,Direita,1.0,...,NaN,2024,5'7,161lbs,83.0,68.0,79.0,86.0,78.0,62.0
222737,Malcom,21,Brazil,82,89,FC Barcelona,€31.5M,€140K,Esquerda,2.0,...,NaN,2023,5'8,163lbs,85.0,87.0,92.0,84.0,74.0,64.0
201400,Rafinha,25,Brazil,82,87,FC Barcelona,€29.5M,€165K,Esquerda,2.0,...,NaN,2020,5'9,157lbs,84.0,71.0,80.0,80.0,67.0,66.0

## Qual é a média de idade dos jogadores nascidos no Brasil
Resposta : 27.62 anos

In [56]:
df_nacionalidade_brasil = df_fifa.query('nacionalidade == "Brazil"')

In [74]:
df_nacionalidade_brasil.groupby("nacionalidade").agg({
   'idade' : np.mean
     
})

                   idade
nacionalidade
Brazil         27.625151

## Qual é o Pais com Maior número de jogadores em Clubes
Resposta: England

In [112]:
df_fifa.head()

,id,nome,idade,nacionalidade,pontuacao_geral,potencial,time,valor,remuneracao,perna_preferencia,...,emprestado_de,validade_contrato,altura,peso,controle_bola,arrancada,agilidade,equilibrio,energia,força
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Esquerda,...,NaN,2021,5'7,159lbs,96.0,91.0,91.0,95.0,72.0,59.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Direita,...,NaN,2022,6'2,183lbs,94.0,89.0,87.0,70.0,88.0,79.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Direita,...,NaN,2022,5'9,150lbs,95.0,94.0,96.0,84.0,81.0,49.0
3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Direita,...,NaN,2020,6'4,168lbs,42.0,57.0,60.0,43.0,43.0,64.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Direita,...,NaN,2023,5'11,154lbs,91.0,78.0,79.0,77.0,90.0,75.0

In [125]:
df_fifa['nacionalidade'].value_counts()

England                 1662
Germany                 1198
Spain                   1072
Argentina                937
France                   914
                        ...
New Caledonia              1
Fiji                       1
São Tomé & Príncipe        1
United Arab Emirates       1
Botswana                   1
Name: nacionalidade, Length: 164, dtype: int64